"""Runs every synthetic claim through the Navigator agent and saves traces.

Requires ANTHROPIC_API_KEY. Writes one JSON file per claim to
agent/data/traces/{claim_id}.json, plus a rollup index at
dashboard/data.js that the static dashboard loads directly (no server
required to view results - see dashboard/README-ish notes in the top-level
README for the alternative FastAPI-served path).
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

from agent.fnol_agent import DEFAULT_MODEL, process_claim

CLAIMS_DIR = Path(__file__).parent / "data" / "claims"
TRACES_DIR = Path(__file__).parent / "data" / "traces"
DASHBOARD_DATA_JS = Path(__file__).parent.parent / "dashboard" / "data.js"


def load_claims() -> list[dict]:
    claims = []
    for path in sorted(CLAIMS_DIR.glob("*.json")):
        claims.append(json.loads(path.read_text()))
    return claims


def run_all(model: str = DEFAULT_MODEL) -> list[dict]:
    TRACES_DIR.mkdir(parents=True, exist_ok=True)
    claims = load_claims()
    summaries = []

    for i, claim in enumerate(claims, start=1):
        claim_id = claim["claim_id"]
        print(f"[{i}/{len(claims)}] {claim_id} ... ", end="", flush=True)
        start = time.perf_counter()
        try:
            trace = process_claim(claim_id, claim["submitted_text"], model=model)
        except Exception as exc:  # noqa: BLE001 - surface any failure per-claim, keep the batch going
            print(f"FAILED ({exc})")
            continue
        elapsed = time.perf_counter() - start

        trace_dict = trace.model_dump(mode="json")
        trace_dict["edge_case"] = claim.get("edge_case")
        trace_dict["latency_seconds"] = round(elapsed, 2)

        out_path = TRACES_DIR / f"{claim_id}.json"
        out_path.write_text(json.dumps(trace_dict, indent=2))

        decision = trace_dict.get("decision") or "ERROR"
        confidence = trace_dict.get("confidence")
        print(f"{decision} (confidence={confidence}) [{elapsed:.1f}s]")

        summaries.append(
            {
                "claim_id": claim_id,
                "policyholder_name": (trace_dict.get("extracted") or {}).get("policyholder_name"),
                "loss_type": (trace_dict.get("extracted") or {}).get("loss_type"),
                "decision": decision,
                "confidence": confidence,
                "flag_count": len(trace_dict.get("flags") or []),
            }
        )

    DASHBOARD_DATA_JS.parent.mkdir(parents=True, exist_ok=True)
    full_traces = [json.loads((TRACES_DIR / f"{s['claim_id']}.json").read_text()) for s in summaries]
    DASHBOARD_DATA_JS.write_text(
        "// Generated by agent/run_batch.py - do not edit by hand.\n"
        "const FNOL_TRACES = " + json.dumps(full_traces, indent=2) + ";\n"
    )
    print(f"\nWrote {len(summaries)} traces to {TRACES_DIR}")
    print(f"Wrote dashboard data to {DASHBOARD_DATA_JS}")
    return summaries


if __name__ == "__main__":
    model = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MODEL
    run_all(model=model)
